/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JakKorzystacRouteImport } from './routes/jak-korzystac'
import { Route as IndexRouteImport } from './routes/index'

const JakKorzystacRoute = JakKorzystacRouteImport.update({
  id: '/jak-korzystac',
  path: '/jak-korzystac',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jak-korzystac': typeof JakKorzystacRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jak-korzystac': typeof JakKorzystacRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jak-korzystac': typeof JakKorzystacRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jak-korzystac'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jak-korzystac'
  id: '__root__' | '/' | '/jak-korzystac'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JakKorzystacRoute: typeof JakKorzystacRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jak-korzystac': {
      id: '/jak-korzystac'
      path: '/jak-korzystac'
      fullPath: '/jak-korzystac'
      preLoaderRoute: typeof JakKorzystacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JakKorzystacRoute: JakKorzystacRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
